language: node_js
node_js:
  - '0.10'
services:
  - mongodb
  - redis-server
before_script:
  - npm install -g istanbul
  - npm install coveralls
  - npm install mocha-lcov-reporter
script:
  - npm test
  - npm run-script lint
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha -- --recursive -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/lcov-report/index.html
  - rm -rf ./coverage
